name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.3', '8.4', '8.5' ]

    name: Run tests on PHP v${{ matrix.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring,
          coverage: xdebug, pcov
          tools: composer:v2

      - name: Set composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_DIRECTORY=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Restore composer from cache
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run phpunit unit tests with coverage
        run: vendor/bin/phpunit --testsuite=unit --colors=always --testdox --coverage-clover=coverage.xml

      - name: Coverage Check
        uses: ericsizemore/phpunit-coverage-check-action@2.0.0
        with:
          clover_file: 'coverage.xml'
          threshold: 75
